# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d288d142ba2ade2d4208eb0edba326ee"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "volume-discount-borosil-mrp"
handle = "volume-discount-borosil-mrp"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "arshiyas-development-store.myshopify.com"
